### ISSUE TITLE
k8s-operator keep restarting the VSI

### ISSUE THREAD

**Issue by iulianroman** [ibm-hyper-protect/k8s-operator-hpcr#79]
On a newly deployed  VS , I noticed the following messages on the K8S-operator logs: 
```shell
2023/06/01 11:34:35 synchronizing onprem VSI ...
2023/06/01 11:34:35 Merging ConfigMap [vpc-onprem-configmap] ...
2023/06/01 11:34:35 Data Disk [notarydisk] is not in ready state, ignoring, cause: [Ready]
2023/06/01 11:34:35 synchronizing onprem VSI ...
[GIN] 2023/06/01 - 11:34:35 | 200 |     785.296µs |     10.42.0.150 | POST     "/onprem/sync"
2023/06/01 11:34:35 synchronizing data disk ...
[GIN] 2023/06/01 - 11:34:35 | 200 |     175.357µs |     10.42.0.150 | POST     "/datadisk/sync"
2023/06/01 11:34:36 Domain [94b8b839-f517-4913-a81d-c79e637c564a] is already up to date, hashes match.
2023/06/01 11:34:36 Domain [94b8b839-f517-4913-a81d-c79e637c564a] is running, fetching logs ...
2023/06/01 11:34:36 Error [procedure interrupted while awaiting response]
``` 

On the KVM host i see that the VM is restarting every few minutes:

```shell
virsh list | grep "94b8b839-f517-4913-a81d-c79e637c564a"
 126   94b8b839-f517-4913-a81d-c79e637c564a   running
```

**Comment by CarstenLeue** [comment]
@iulianroman the operator checks on a regular basis if the configuration of the VSI has changed. If is has changed, then the operator will restart the VSI, because that's the only way to apply changes.

In the case above it looks like the operator detects a "change" in the data disk, `Data Disk [notarydisk] is not in ready state, ignoring, cause: [Ready]`.

Since the data disk is not ready, the VSI config is considered to be without a data disk, this is a change from the previous state (a data disk included) and as a result the VSI is restarted.

So the question is why the data disk is not considered ready, since that is the root cause.

The error message `procedure interrupted while awaiting response` suggests that this is due to a failing SSH connection. 

@iulianroman does the version of the operator contain https://github.com/ibm-hyper-protect/k8s-operator-hpcr/pull/66 which is supposed to fix the ssh problem?

**Comment by CarstenLeue** [comment]
I believe it's a race condition on the lock https://github.com/ibm-hyper-protect/k8s-operator-hpcr/blob/main/server/datadisk/datadisk.go#L41

since that is a central lock. Reason to have locks in the first place is that the "create VSI" operation turned out to be very time consuming and it took longer than the retry-period.
But for data disks this is probably not the case and we could remove the lock altogether to avoid this situation.
